config/urls.py
from config.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

app_name = "core"

rooms/urls.py
from django.urls import path
from rooms import views as room_views

urlpatterns = [
    path("<int:pk>/", room_views.room_details, name="details"),
    path("<int:pk>/edit/", room_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", room_views.RoomPhotosView.as_view(), name="photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        room_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        room_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("<int:pk>/photos/add", room_views.AddPhotoView.as_view(), name="add-photo"),
    path("search/", room_views.SearchView.as_view(), name="search"),
    path("create/", room_views.CreateRoomView.as_view(), name="create"),
]

app_name = "rooms"

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

app_name = "users"

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <span>
            {% trans "Please don't copy us." %}
        </span>
        <span>&copy; 2021 Minhyeok Son. {% trans "All rights reserved" %}.</span>
    </div>
    <div class="mt-10 flex">
        {% get_current_language as LANGUAGE_CODE %}
        {{LANGUAGE_CODE}}
        <select class="w-1/5 h-8" id="js-lang">
            <option value="en"
                {% if LANGUAGE_CODE == 'en' %}
                selected
                {% endif %}
            >English</option>
            <option value="kr"
                {% if LANGUAGE_CODE == 'ko' %}
                    selected
                {% endif %}
            >Korean</option>
        </select>
    </div>
</footer> 

templates/partials/messages.html
{% if messages %}
    <ul class="absolute top-0 left-0 right-0 flex justify-center message">
        {% for message in messages %}
            <li class="z-10 w-3/12 text-center font-medium bg-gray-700 rounded-full text-white py-4 px-6 {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %} 

templates/partials/nav.html
<ul class="flex h-full items-center">
    {% if user.is_authenticated %}
        <li class="nav-link">
            <a href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    Stop hosting
                {% else %}
                    Start hosting
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav-link"><a href="{% url 'rooms:create' %}">Create Room</a></li>
        {% endif %}
        <li class="nav-link"><a href="{{user.get_absolute_url}}">Profile</a></li>
        <li class="nav-link"><a href="{% url 'users:logout' %}">Log out</a></li>
    {% else %}
        <li class="nav-link "><a href="{% url 'users:login' %}">Log in</a></li>
        <li class="nav-link"><a href="{% url 'users:signup' %}">Sign up</a></li>
    {% endif %}

</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a class="btn border-2  text-gray-700 mb-2 border-gray-700" href="{% url 'users:github-login' %}">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>Continue with Github
    </a>
    <a class="btn border text-yellow-800 mb-2 border-yellow-400 bg-yellow-400" href="{% url 'users:kakao-login' %}">
        <i class="fas fa-comment mr-2 fa-lg"></i>Continue with Kakao
    </a>
</div>
<div class="flex items-center w-full my-4">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div> 