config/urls.py
from config.settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

app_name = "core"

rooms/urls.py
from django.urls import path
from rooms import views as room_views

urlpatterns = [
    path("<int:pk>/", room_views.room_details, name="details"),
    path("<int:pk>/edit/", room_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", room_views.RoomPhotosView.as_view(), name="photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        room_views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        room_views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("<int:pk>/photos/add", room_views.AddPhotoView.as_view(), name="add-photo"),
    path("search/", room_views.SearchView.as_view(), name="search"),
    path("create/", room_views.CreateRoomView.as_view(), name="create"),
]

app_name = "rooms"

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

app_name = "users"

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body class="text-gray-800 mt-24 font-light">
    <div class="flex items-center justify-between p-4 bg-white fixed w-full inset-0 h-20">
        <a href="{% url 'core:home' %}">
            <img class ="w-12" src="{% static 'image/logo.png' %}" alt="logo">
        </a>
        {% block search %}
        {% include 'partials/messages.html' %}
        <header>
            <form method = "get" action="{% url 'rooms:search' %}">
                <input class="border p-2 rounded-2xl border-gray-300 placeholder-gray-900 text-sm w-80 px-5 shadow hover:shadow-lg focus:outline-none" name="city" type="text" 
                placeholder="{% trans 'Search by City' %}">
            </form>
        </header>
        {% endblock search %}
        {% include "partials/nav.html" %}
    </div>
    
    
    {% block content %}
    {% endblock %}
    {% include 'partials/footer.html' %}
    <script>
        const langSelect = document.getElementById("js-lang");
        const handleLangChange = () => {
            const selected = langSelect.value;
            fetch(`{% url 'users:switch-language' %}?lang=${selected}`).then(() => window.location.reload());
        }
        langSelect.addEventListener("change", handleLangChange);
    </script>
</body>
</html>